### ISSUE TITLE
Replacing html

### ISSUE THREAD

**Issue by Programming4life** [tec27/node-argyle#3]
How can I intercept and replace content.

``` javascript
var argyle = require('argyle');

var server = argyle(8080, '127.0.0.1');
server.on('connected', function(req, dest) {
    // req.pipe(dest);
    // dest.pipe(req);

    req.on('data', function(chunk) {
        dest.write(chunk);
    });

    dest.on('data', function(chunk) {
        req.write(chunk);
        console.log(chunk.toString('utf8'));
    });
});
```

Output:

```
nis%\=oJe,|o)jGQF8!*iw:xM4<S#IwPx]4G[V,a._Eun$)%-flB>]s~/o2y2U>t{(
```

I want the output to be html.
How can I get the html and content type?

**Comment by samuel-allan** [comment]
If you are using HTTPS on the client/server-side you can't.
In the case that you are using HTTP, the information could be gzipped, can you give more context on what particular site you are experiencing this problem with?
